# Generated by Django 5.2.7 on 2025-12-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0003_alter_class_options_alter_dailymenu_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklybreakfasts',
            options={'verbose_name': 'Еженедельные выборы', 'verbose_name_plural': 'Еженедельный выбор'},
        ),
        migrations.AddField(
            model_name='dish',
            name='short_name',
            field=models.CharField(default='', max_length=100, verbose_name='Короткое название блюда'),
            preserve_default=False,
        ),
    ]
