# Generated by Django 5.2.7 on 2025-12-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0004_alter_weeklybreakfasts_options_dish_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AddField(
            model_name='class',
            name='number_of_pupils',
            field=models.IntegerField(default=0, verbose_name='Количество учеников'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Название блюда'),
        ),
    ]
